# Generated by Django 4.0.5 on 2022-07-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='detalhes',
        ),
    ]
