# Generated by Django 4.0.5 on 2022-07-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_profile_user_profile_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='data_nascimento',
        ),
    ]
