# Generated by Django 4.0.5 on 2022-07-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_birth_date_profile_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usuario',
            new_name='user',
        ),
    ]
