# Generated by Django 4.0.5 on 2022-07-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_usuario_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
